name: Build, test, release and publish


on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [16.15.1]

    steps:

      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/VolteraInc


      # Install
      # Note: skip scripts, so malicious scripts can't steal our token
      - name: Install
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_READ }}

      # Post install
      - name: Prepare
        run: npm rebuild && npm run prepare --if-present

      # Build
      - name: Build
        run: npm run build --if-present

      # Test
      # Note: The ubuntu image used by github actions has xvfb is installed, but DISPLAY
      #       is not configured by default. Tests that use electron require DISPLAY
      #       to be set they will hang. xvfb-run is a simply way of doing this.
      - name: Test
        run: xvfb-run --auto-servernum npm test --if-present

      # Publish
      - name: Publish (if the tag starts with v)
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT_WRITE}}

      # Create a release based on the version of container published
      - name: Create Release (if tag starts with v)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
